package com.xu.flashsale.dataobject;

public class UserPasswordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.id
     *
     * @mbg.generated Sun May 10 00:59:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.encrp_password
     *
     * @mbg.generated Sun May 10 00:59:32 CST 2020
     */
    private String encrpPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.user_id
     *
     * @mbg.generated Sun May 10 00:59:32 CST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.id
     *
     * @return the value of user_password.id
     *
     * @mbg.generated Sun May 10 00:59:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.id
     *
     * @param id the value for user_password.id
     *
     * @mbg.generated Sun May 10 00:59:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.encrp_password
     *
     * @return the value of user_password.encrp_password
     *
     * @mbg.generated Sun May 10 00:59:32 CST 2020
     */
    public String getEncrpPassword() {
        return encrpPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.encrp_password
     *
     * @param encrpPassword the value for user_password.encrp_password
     *
     * @mbg.generated Sun May 10 00:59:32 CST 2020
     */
    public void setEncrpPassword(String encrpPassword) {
        this.encrpPassword = encrpPassword == null ? null : encrpPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.user_id
     *
     * @return the value of user_password.user_id
     *
     * @mbg.generated Sun May 10 00:59:32 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.user_id
     *
     * @param userId the value for user_password.user_id
     *
     * @mbg.generated Sun May 10 00:59:32 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}